---
driver:
  name: vagrant
  vm_hostname: <%= ENV['GS'] %>
  customize:
    memory: <%= ENV['GSR'] %>
    cpus: <%= ENV['GSC'] %>
    name: <%= ENV['GS'] %>
  network:
   - ['private_network', ip: <%= ENV['GSP'] %>]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  # always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: mycsc-7.6

suites:
  - name: wgisrv
    run_list:
      - recipe[wgisrv::make_nc_wg]
      # - recipe[wgisrv::create_scripts]
    verifier:
      inspec_tests:
        - test/integration/default
