---
driver:
  name: vagrant
  vm_hostname: <%= ENV['GS'] %>
  customize:
    memory: <%= ENV['GSR'] %>
    cpus: <%= ENV['GSC'] %>
    name: <%= ENV['GS'] %>
    createhd:
      - filename: disk1.vmdk
        size: <%= ENV['GSD'] %>
    storagectl:
      - name: SATA Controller
        portcount: 1
    storageattach:
      - storagectl: SATA Controller
        port: 1
        device: 0
        type: hdd
        medium: disk1.vmdk
  network:
   - ['private_network', ip: <%= ENV['GSP'] %>]

provisioner:
  name: chef_zero
  product_name: chef
  product_version: <%= ENV['chef_release'] %>
  install_strategy: always
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  # always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: mycentos7
    provisioner:
      download_url: http://10.1.1.30/media/chef-<%= ENV['chef_release'] %>-1.el7.x86_64.rpm

suites:
  - name: wgisrv
    run_list:
      - recipe[wgisrv::make_nc_wg]
      # - recipe[wgisrv::create_scripts]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
