AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Rakefile
    - Thorfile
    - Guardfile
  Exclude:
    - vendor/**/*

Documentation:
  Enabled: false

Style/GlobalVars:
  AllowedVariables: [$access_token]
