default['wgisrv'].tap do |wgs|
  wgs['app_dir']   = '/apps'
  wgs['ng_dir']    = "#{node['wgisrv']['app_dir']}/webgui"
  wgs['ng_home']   = '/home/webgui'
  wgs['nc_home']   = '/home/netcool'
  wgs['in_dir']    = "#{node['wgisrv']['app_dir']}/install"
  wgs['media_dir'] = "#{node['wgisrv']['app_dir']}/media"
  wgs['shr_dir']   = "#{node['wgisrv']['app_dir']}/IMShared"
  wgs['was_dir']   = "#{node['wgisrv']['app_dir']}/WebSphere/AppServer"
  wgs['jaz_dir']   = "#{node['wgisrv']['app_dir']}/JazzSM"
  wgs['jaz_pid']   = "#{node['wgisrv']['jaz_dir']}/profile/logs/server1/server1.pid"
  wgs['cog_loc']   = "#{node['wgisrv']['in_dir']}/TCRCognos"
  wgs['rpt_bak']   = "#{node['wgisrv']['jaz_dir']}/rpt_bak"
  wgs['packages']  = %w(motif.i686 compat-glibc libpng12.i686 nspr.i686)
  wgs['packages1'] = %w(nss)
  wgs['packages2'] = %w(nss.i686)
  wgs['temp_dir']  = '/tmp'
  wgs['media_url'] = 'http://10.1.1.30/media'
  wgs['lv_name']   = 'lvnc'
  wgs['lv_size']   = '40G'
  wgs['nc_act']    = 'netcool'
  wgs['nc_grp']    = 'ncoadmin'
  wgs['root_pwd']  = 'nc0Adm1n'
  wgs['was_act']   = 'smadmin'
  wgs['was_epwd']  = 'U4DQSKB8w2r6uZlbcdHAPQ=='
  wgs['dash_pwd']  = 'P@ssw0rd'
  wgs['instance']  = 'inst1'
  wgs['db2_epwd']  = 'U4DQSKB8w2r6uZlbcdHAPQ=='
  wgs['db2_port']  = '60008'
  wgs['db2_act']   = 'tcr001'
  wgs['db2_db']    = 'TCRDB'
  wgs['ncoms']     = 'NCO'
  wgs['os_port']   = '4100'
  wgs['pa_port']   = '4200'
  wgs['OS']        = 'eao'
  wgs['OSP']       = '10.1.1.40'
  wgs['GS']        = 'eag'
  wgs['DS']        = 'ead'
  wgs['DSP']       = '10.1.1.43'
end
